# Generated by Django 2.2.1 on 2019-05-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigant', '0002_auto_20190528_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='CarsGuru/image_folder/product_image'),
        ),
    ]
