# Generated by Django 2.1.5 on 2019-03-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigant', '0002_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigant.Category')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigant.Mark')),
            ],
        ),
    ]
