# Generated by Django 2.2.1 on 2019-05-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigant', '0003_auto_20190529_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gigant.Car'),
        ),
    ]
