# Generated by Django 2.1.5 on 2019-04-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigant', '0003_prducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prducts',
            new_name='Product',
        ),
    ]
