# Generated by Django 2.1.5 on 2019-04-03 18:39

from django.db import migrations, models
import gigant.models


class Migration(migrations.Migration):

    dependencies = [
        ('gigant', '0004_auto_20190403_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=gigant.models.image_folder),
        ),
    ]
