# Generated by Django 2.1.7 on 2019-05-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigant', '0007_auto_20190510_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
