# Generated by Django 2.1.7 on 2019-05-20 19:08

from django.db import migrations, models
import django.db.models.deletion
import gigant.models


class Migration(migrations.Migration):

    dependencies = [
        ('gigant', '0010_auto_20190519_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=gigant.models.image_folder)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigant.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mark',
        ),
        migrations.RenameModel(
            old_name='Mark',
            new_name='Products',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='car',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigant.Products'),
        ),
    ]
