# Generated by Django 2.1.7 on 2019-05-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigant', '0012_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='product',
        ),
    ]
